version: 0.2

env:
  variables:
    IMAGE_WPSCAN_BASE: "base/wpscan-base"

phases:
  install:
    commands:
      - export DOCKER_CLI_EXPERIMENTAL=enabled
  pre_build:
    commands:
      - echo Setting environment variables
      - BUILD_OPT="--no-cache --pull"
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - REGISTORY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
  build:
    commands:
      - echo Build wpscan base image manifest started on `date`
      - TAG=${WPSCAN_VERSION}
      # version tag
      - docker manifest create ${REGISTORY}/${IMAGE_WPSCAN_BASE}:${TAG} ${REGISTORY}/${IMAGE_WPSCAN_BASE}:${TAG}_linux_amd64 ${REGISTORY}/${IMAGE_WPSCAN_BASE}:${TAG}_linux_arm64
      - docker manifest annotate --arch amd64 ${REGISTORY}/${IMAGE_WPSCAN_BASE}:${TAG} ${REGISTORY}/${IMAGE_WPSCAN_BASE}:${TAG}_linux_amd64
      - docker manifest annotate --arch arm64 ${REGISTORY}/${IMAGE_WPSCAN_BASE}:${TAG} ${REGISTORY}/${IMAGE_WPSCAN_BASE}:${TAG}_linux_arm64
      # latest
      - docker manifest create ${REGISTORY}/${IMAGE_WPSCAN_BASE}:latest ${REGISTORY}/${IMAGE_WPSCAN_BASE}:${TAG}_linux_amd64 ${REGISTORY}/${IMAGE_WPSCAN_BASE}:${TAG}_linux_arm64
      - docker manifest annotate --arch amd64 ${REGISTORY}/${IMAGE_WPSCAN_BASE}:latest ${REGISTORY}/${IMAGE_WPSCAN_BASE}:${TAG}_linux_amd64
      - docker manifest annotate --arch arm64 ${REGISTORY}/${IMAGE_WPSCAN_BASE}:latest ${REGISTORY}/${IMAGE_WPSCAN_BASE}:${TAG}_linux_arm64

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker manifest...
      # push manifests
      - docker manifest push ${REGISTORY}/${IMAGE_WPSCAN_BASE}:${TAG}
      - docker manifest push ${REGISTORY}/${IMAGE_WPSCAN_BASE}:latest
      # inspect
      - docker manifest inspect ${REGISTORY}/${IMAGE_WPSCAN_BASE}:${TAG}
      - docker manifest inspect ${REGISTORY}/${IMAGE_WPSCAN_BASE}:latest
