batch:
  build-graph:
    - identifier: build_amd64
      buildspec: codebuild/wpscan-base-image/buildspec-image.yml
      env:
        compute-type: BUILD_GENERAL1_SMALL
        image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        privileged-mode: true
        type: LINUX_CONTAINER
        variables:
          OS: linux
          ARCH: amd64
          WPSCAN_VERSION: 9acac36b85943fdf56c35266f1ecaebabf9d8436
    - identifier: build_arm64
      buildspec: codebuild/wpscan-base-image/buildspec-image.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
        image: aws/codebuild/amazonlinux2-aarch64-standard:2.0
        privileged-mode: true
        type: ARM_CONTAINER
        variables:
          OS: linux
          ARCH: arm64
          WPSCAN_VERSION: 9acac36b85943fdf56c35266f1ecaebabf9d8436
    - identifier: build_manifest
      buildspec: codebuild/wpscan-base-image/buildspec-manifest.yml
      env:
        compute-type: BUILD_GENERAL1_SMALL
        image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        privileged-mode: true
        type: LINUX_CONTAINER
        variables:
          WPSCAN_VERSION: 9acac36b85943fdf56c35266f1ecaebabf9d8436
      depend-on:
        - build_amd64
        - build_arm64


