// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: diagnosis/services.proto

package diagnosis

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// DiagnosisDataSourceService
type ListDiagnosisDataSourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId uint32 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListDiagnosisDataSourceRequest) Reset() {
	*x = ListDiagnosisDataSourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diagnosis_services_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDiagnosisDataSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDiagnosisDataSourceRequest) ProtoMessage() {}

func (x *ListDiagnosisDataSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diagnosis_services_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDiagnosisDataSourceRequest.ProtoReflect.Descriptor instead.
func (*ListDiagnosisDataSourceRequest) Descriptor() ([]byte, []int) {
	return file_diagnosis_services_proto_rawDescGZIP(), []int{0}
}

func (x *ListDiagnosisDataSourceRequest) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ListDiagnosisDataSourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListDiagnosisDataSourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiagnosisDataSource []*DiagnosisDataSource `protobuf:"bytes,1,rep,name=diagnosis_data_source,json=diagnosisDataSource,proto3" json:"diagnosis_data_source,omitempty"`
}

func (x *ListDiagnosisDataSourceResponse) Reset() {
	*x = ListDiagnosisDataSourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diagnosis_services_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDiagnosisDataSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDiagnosisDataSourceResponse) ProtoMessage() {}

func (x *ListDiagnosisDataSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diagnosis_services_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDiagnosisDataSourceResponse.ProtoReflect.Descriptor instead.
func (*ListDiagnosisDataSourceResponse) Descriptor() ([]byte, []int) {
	return file_diagnosis_services_proto_rawDescGZIP(), []int{1}
}

func (x *ListDiagnosisDataSourceResponse) GetDiagnosisDataSource() []*DiagnosisDataSource {
	if x != nil {
		return x.DiagnosisDataSource
	}
	return nil
}

type GetDiagnosisDataSourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId             uint32 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	DiagnosisDataSourceId uint32 `protobuf:"varint,2,opt,name=diagnosis_data_source_id,json=diagnosisDataSourceId,proto3" json:"diagnosis_data_source_id,omitempty"`
}

func (x *GetDiagnosisDataSourceRequest) Reset() {
	*x = GetDiagnosisDataSourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diagnosis_services_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDiagnosisDataSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiagnosisDataSourceRequest) ProtoMessage() {}

func (x *GetDiagnosisDataSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diagnosis_services_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiagnosisDataSourceRequest.ProtoReflect.Descriptor instead.
func (*GetDiagnosisDataSourceRequest) Descriptor() ([]byte, []int) {
	return file_diagnosis_services_proto_rawDescGZIP(), []int{2}
}

func (x *GetDiagnosisDataSourceRequest) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *GetDiagnosisDataSourceRequest) GetDiagnosisDataSourceId() uint32 {
	if x != nil {
		return x.DiagnosisDataSourceId
	}
	return 0
}

type GetDiagnosisDataSourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiagnosisDataSource *DiagnosisDataSource `protobuf:"bytes,1,opt,name=diagnosis_data_source,json=diagnosisDataSource,proto3" json:"diagnosis_data_source,omitempty"`
}

func (x *GetDiagnosisDataSourceResponse) Reset() {
	*x = GetDiagnosisDataSourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diagnosis_services_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDiagnosisDataSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiagnosisDataSourceResponse) ProtoMessage() {}

func (x *GetDiagnosisDataSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diagnosis_services_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiagnosisDataSourceResponse.ProtoReflect.Descriptor instead.
func (*GetDiagnosisDataSourceResponse) Descriptor() ([]byte, []int) {
	return file_diagnosis_services_proto_rawDescGZIP(), []int{3}
}

func (x *GetDiagnosisDataSourceResponse) GetDiagnosisDataSource() *DiagnosisDataSource {
	if x != nil {
		return x.DiagnosisDataSource
	}
	return nil
}

type PutDiagnosisDataSourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId           uint32                        `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	DiagnosisDataSource *DiagnosisDataSourceForUpsert `protobuf:"bytes,2,opt,name=diagnosis_data_source,json=diagnosisDataSource,proto3" json:"diagnosis_data_source,omitempty"`
}

func (x *PutDiagnosisDataSourceRequest) Reset() {
	*x = PutDiagnosisDataSourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diagnosis_services_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutDiagnosisDataSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutDiagnosisDataSourceRequest) ProtoMessage() {}

func (x *PutDiagnosisDataSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diagnosis_services_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutDiagnosisDataSourceRequest.ProtoReflect.Descriptor instead.
func (*PutDiagnosisDataSourceRequest) Descriptor() ([]byte, []int) {
	return file_diagnosis_services_proto_rawDescGZIP(), []int{4}
}

func (x *PutDiagnosisDataSourceRequest) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *PutDiagnosisDataSourceRequest) GetDiagnosisDataSource() *DiagnosisDataSourceForUpsert {
	if x != nil {
		return x.DiagnosisDataSource
	}
	return nil
}

type PutDiagnosisDataSourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId           uint32               `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	DiagnosisDataSource *DiagnosisDataSource `protobuf:"bytes,2,opt,name=diagnosis_data_source,json=diagnosisDataSource,proto3" json:"diagnosis_data_source,omitempty"`
}

func (x *PutDiagnosisDataSourceResponse) Reset() {
	*x = PutDiagnosisDataSourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diagnosis_services_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutDiagnosisDataSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutDiagnosisDataSourceResponse) ProtoMessage() {}

func (x *PutDiagnosisDataSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diagnosis_services_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutDiagnosisDataSourceResponse.ProtoReflect.Descriptor instead.
func (*PutDiagnosisDataSourceResponse) Descriptor() ([]byte, []int) {
	return file_diagnosis_services_proto_rawDescGZIP(), []int{5}
}

func (x *PutDiagnosisDataSourceResponse) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *PutDiagnosisDataSourceResponse) GetDiagnosisDataSource() *DiagnosisDataSource {
	if x != nil {
		return x.DiagnosisDataSource
	}
	return nil
}

type DeleteDiagnosisDataSourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId             uint32 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	DiagnosisDataSourceId uint32 `protobuf:"varint,2,opt,name=diagnosis_data_source_id,json=diagnosisDataSourceId,proto3" json:"diagnosis_data_source_id,omitempty"`
}

func (x *DeleteDiagnosisDataSourceRequest) Reset() {
	*x = DeleteDiagnosisDataSourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diagnosis_services_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDiagnosisDataSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDiagnosisDataSourceRequest) ProtoMessage() {}

func (x *DeleteDiagnosisDataSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diagnosis_services_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDiagnosisDataSourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteDiagnosisDataSourceRequest) Descriptor() ([]byte, []int) {
	return file_diagnosis_services_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteDiagnosisDataSourceRequest) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *DeleteDiagnosisDataSourceRequest) GetDiagnosisDataSourceId() uint32 {
	if x != nil {
		return x.DiagnosisDataSourceId
	}
	return 0
}

// JiraSettingService
type ListJiraSettingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId             uint32 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	DiagnosisDataSourceId uint32 `protobuf:"varint,2,opt,name=diagnosis_data_source_id,json=diagnosisDataSourceId,proto3" json:"diagnosis_data_source_id,omitempty"`
}

func (x *ListJiraSettingRequest) Reset() {
	*x = ListJiraSettingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diagnosis_services_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListJiraSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJiraSettingRequest) ProtoMessage() {}

func (x *ListJiraSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diagnosis_services_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJiraSettingRequest.ProtoReflect.Descriptor instead.
func (*ListJiraSettingRequest) Descriptor() ([]byte, []int) {
	return file_diagnosis_services_proto_rawDescGZIP(), []int{7}
}

func (x *ListJiraSettingRequest) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ListJiraSettingRequest) GetDiagnosisDataSourceId() uint32 {
	if x != nil {
		return x.DiagnosisDataSourceId
	}
	return 0
}

type ListJiraSettingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JiraSetting []*JiraSetting `protobuf:"bytes,1,rep,name=jira_setting,json=jiraSetting,proto3" json:"jira_setting,omitempty"`
}

func (x *ListJiraSettingResponse) Reset() {
	*x = ListJiraSettingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diagnosis_services_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListJiraSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJiraSettingResponse) ProtoMessage() {}

func (x *ListJiraSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diagnosis_services_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJiraSettingResponse.ProtoReflect.Descriptor instead.
func (*ListJiraSettingResponse) Descriptor() ([]byte, []int) {
	return file_diagnosis_services_proto_rawDescGZIP(), []int{8}
}

func (x *ListJiraSettingResponse) GetJiraSetting() []*JiraSetting {
	if x != nil {
		return x.JiraSetting
	}
	return nil
}

type GetJiraSettingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId     uint32 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	JiraSettingId uint32 `protobuf:"varint,2,opt,name=jira_setting_id,json=jiraSettingId,proto3" json:"jira_setting_id,omitempty"`
}

func (x *GetJiraSettingRequest) Reset() {
	*x = GetJiraSettingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diagnosis_services_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJiraSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJiraSettingRequest) ProtoMessage() {}

func (x *GetJiraSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diagnosis_services_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJiraSettingRequest.ProtoReflect.Descriptor instead.
func (*GetJiraSettingRequest) Descriptor() ([]byte, []int) {
	return file_diagnosis_services_proto_rawDescGZIP(), []int{9}
}

func (x *GetJiraSettingRequest) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *GetJiraSettingRequest) GetJiraSettingId() uint32 {
	if x != nil {
		return x.JiraSettingId
	}
	return 0
}

type GetJiraSettingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JiraSetting *JiraSetting `protobuf:"bytes,1,opt,name=jira_setting,json=jiraSetting,proto3" json:"jira_setting,omitempty"`
}

func (x *GetJiraSettingResponse) Reset() {
	*x = GetJiraSettingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diagnosis_services_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJiraSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJiraSettingResponse) ProtoMessage() {}

func (x *GetJiraSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diagnosis_services_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJiraSettingResponse.ProtoReflect.Descriptor instead.
func (*GetJiraSettingResponse) Descriptor() ([]byte, []int) {
	return file_diagnosis_services_proto_rawDescGZIP(), []int{10}
}

func (x *GetJiraSettingResponse) GetJiraSetting() *JiraSetting {
	if x != nil {
		return x.JiraSetting
	}
	return nil
}

type PutJiraSettingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId   uint32                `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	JiraSetting *JiraSettingForUpsert `protobuf:"bytes,2,opt,name=jira_setting,json=jiraSetting,proto3" json:"jira_setting,omitempty"`
}

func (x *PutJiraSettingRequest) Reset() {
	*x = PutJiraSettingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diagnosis_services_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutJiraSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutJiraSettingRequest) ProtoMessage() {}

func (x *PutJiraSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diagnosis_services_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutJiraSettingRequest.ProtoReflect.Descriptor instead.
func (*PutJiraSettingRequest) Descriptor() ([]byte, []int) {
	return file_diagnosis_services_proto_rawDescGZIP(), []int{11}
}

func (x *PutJiraSettingRequest) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *PutJiraSettingRequest) GetJiraSetting() *JiraSettingForUpsert {
	if x != nil {
		return x.JiraSetting
	}
	return nil
}

type PutJiraSettingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JiraSetting *JiraSetting `protobuf:"bytes,1,opt,name=jira_setting,json=jiraSetting,proto3" json:"jira_setting,omitempty"`
}

func (x *PutJiraSettingResponse) Reset() {
	*x = PutJiraSettingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diagnosis_services_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutJiraSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutJiraSettingResponse) ProtoMessage() {}

func (x *PutJiraSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diagnosis_services_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutJiraSettingResponse.ProtoReflect.Descriptor instead.
func (*PutJiraSettingResponse) Descriptor() ([]byte, []int) {
	return file_diagnosis_services_proto_rawDescGZIP(), []int{12}
}

func (x *PutJiraSettingResponse) GetJiraSetting() *JiraSetting {
	if x != nil {
		return x.JiraSetting
	}
	return nil
}

type DeleteJiraSettingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId     uint32 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	JiraSettingId uint32 `protobuf:"varint,2,opt,name=jira_setting_id,json=jiraSettingId,proto3" json:"jira_setting_id,omitempty"`
}

func (x *DeleteJiraSettingRequest) Reset() {
	*x = DeleteJiraSettingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diagnosis_services_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteJiraSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJiraSettingRequest) ProtoMessage() {}

func (x *DeleteJiraSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diagnosis_services_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJiraSettingRequest.ProtoReflect.Descriptor instead.
func (*DeleteJiraSettingRequest) Descriptor() ([]byte, []int) {
	return file_diagnosis_services_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteJiraSettingRequest) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *DeleteJiraSettingRequest) GetJiraSettingId() uint32 {
	if x != nil {
		return x.JiraSettingId
	}
	return 0
}

// KICK Diagnosis
type InvokeScanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId     uint32 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	JiraSettingId uint32 `protobuf:"varint,2,opt,name=jira_setting_id,json=jiraSettingId,proto3" json:"jira_setting_id,omitempty"`
}

func (x *InvokeScanRequest) Reset() {
	*x = InvokeScanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diagnosis_services_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvokeScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeScanRequest) ProtoMessage() {}

func (x *InvokeScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diagnosis_services_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeScanRequest.ProtoReflect.Descriptor instead.
func (*InvokeScanRequest) Descriptor() ([]byte, []int) {
	return file_diagnosis_services_proto_rawDescGZIP(), []int{14}
}

func (x *InvokeScanRequest) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *InvokeScanRequest) GetJiraSettingId() uint32 {
	if x != nil {
		return x.JiraSettingId
	}
	return 0
}

type InvokeScanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *InvokeScanResponse) Reset() {
	*x = InvokeScanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diagnosis_services_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvokeScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeScanResponse) ProtoMessage() {}

func (x *InvokeScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diagnosis_services_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeScanResponse.ProtoReflect.Descriptor instead.
func (*InvokeScanResponse) Descriptor() ([]byte, []int) {
	return file_diagnosis_services_proto_rawDescGZIP(), []int{15}
}

func (x *InvokeScanResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_diagnosis_services_proto protoreflect.FileDescriptor

var file_diagnosis_services_proto_rawDesc = []byte{
	0x0a, 0x18, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x64, 0x69, 0x61, 0x67,
	0x6e, 0x6f, 0x73, 0x69, 0x73, 0x1a, 0x18, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73,
	0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a, 0x1e,
	0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61, 0x74,
	0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x75, 0x0a, 0x1f, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73,
	0x69, 0x73, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x15, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69,
	0x73, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x2e,
	0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x13, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x77, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x44,
	0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x18, 0x64, 0x69, 0x61, 0x67,
	0x6e, 0x6f, 0x73, 0x69, 0x73, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x15, 0x64, 0x69, 0x61, 0x67,
	0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49,
	0x64, 0x22, 0x74, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69,
	0x73, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x15, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x2e, 0x44,
	0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x13, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61, 0x74,
	0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x9b, 0x01, 0x0a, 0x1d, 0x50, 0x75, 0x74, 0x44,
	0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x5b, 0x0a, 0x15, 0x64, 0x69, 0x61, 0x67,
	0x6e, 0x6f, 0x73, 0x69, 0x73, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f,
	0x73, 0x69, 0x73, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61, 0x74,
	0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x46, 0x6f, 0x72, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74,
	0x52, 0x13, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61, 0x74, 0x61, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x93, 0x01, 0x0a, 0x1e, 0x50, 0x75, 0x74, 0x44, 0x69, 0x61,
	0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x52, 0x0a, 0x15, 0x64, 0x69, 0x61, 0x67, 0x6e,
	0x6f, 0x73, 0x69, 0x73, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73,
	0x69, 0x73, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61, 0x74, 0x61,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x13, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69,
	0x73, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x7a, 0x0a, 0x20, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x37,
	0x0a, 0x18, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x15, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61, 0x74, 0x61, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x22, 0x70, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x4a,
	0x69, 0x72, 0x61, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64,
	0x12, 0x37, 0x0a, 0x18, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x15, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61, 0x74,
	0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x22, 0x54, 0x0a, 0x17, 0x4c, 0x69, 0x73,
	0x74, 0x4a, 0x69, 0x72, 0x61, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0c, 0x6a, 0x69, 0x72, 0x61, 0x5f, 0x73, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x69, 0x61,
	0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x2e, 0x4a, 0x69, 0x72, 0x61, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x0b, 0x6a, 0x69, 0x72, 0x61, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x22,
	0x5e, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4a, 0x69, 0x72, 0x61, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x6a, 0x69, 0x72, 0x61, 0x5f,
	0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0d, 0x6a, 0x69, 0x72, 0x61, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x22,
	0x53, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4a, 0x69, 0x72, 0x61, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0c, 0x6a, 0x69, 0x72,
	0x61, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x2e, 0x4a, 0x69, 0x72, 0x61,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x0b, 0x6a, 0x69, 0x72, 0x61, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x22, 0x7a, 0x0a, 0x15, 0x50, 0x75, 0x74, 0x4a, 0x69, 0x72, 0x61, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x42, 0x0a, 0x0c,
	0x6a, 0x69, 0x72, 0x61, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x2e, 0x4a,
	0x69, 0x72, 0x61, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x55, 0x70, 0x73,
	0x65, 0x72, 0x74, 0x52, 0x0b, 0x6a, 0x69, 0x72, 0x61, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x22, 0x53, 0x0a, 0x16, 0x50, 0x75, 0x74, 0x4a, 0x69, 0x72, 0x61, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0c, 0x6a, 0x69,
	0x72, 0x61, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x2e, 0x4a, 0x69, 0x72,
	0x61, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x0b, 0x6a, 0x69, 0x72, 0x61, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x61, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4a,
	0x69, 0x72, 0x61, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64,
	0x12, 0x26, 0x0a, 0x0f, 0x6a, 0x69, 0x72, 0x61, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x6a, 0x69, 0x72, 0x61, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x11, 0x49, 0x6e, 0x76, 0x6f,
	0x6b, 0x65, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f,
	0x6a, 0x69, 0x72, 0x61, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x6a, 0x69, 0x72, 0x61, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x12, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x53, 0x63,
	0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x32, 0xbe, 0x07, 0x0a, 0x10, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73,
	0x69, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x72, 0x0a, 0x17, 0x4c, 0x69, 0x73,
	0x74, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x29, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2a, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6f, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61, 0x74,
	0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x28, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f,
	0x73, 0x69, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73,
	0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x29, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6f,
	0x0a, 0x16, 0x50, 0x75, 0x74, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x28, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x6e,
	0x6f, 0x73, 0x69, 0x73, 0x2e, 0x50, 0x75, 0x74, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69,
	0x73, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x29, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x2e, 0x50,
	0x75, 0x74, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61, 0x74, 0x61, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x62, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73,
	0x69, 0x73, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x2b, 0x2e, 0x64,
	0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44,
	0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x69, 0x72, 0x61, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x21, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73,
	0x69, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x69, 0x72, 0x61, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x64, 0x69, 0x61, 0x67,
	0x6e, 0x6f, 0x73, 0x69, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x69, 0x72, 0x61, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x57, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4a, 0x69, 0x72, 0x61, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x12, 0x20, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x4a, 0x69, 0x72, 0x61, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x4a, 0x69, 0x72, 0x61, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x0e, 0x50, 0x75, 0x74, 0x4a,
	0x69, 0x72, 0x61, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x2e, 0x64, 0x69, 0x61,
	0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x2e, 0x50, 0x75, 0x74, 0x4a, 0x69, 0x72, 0x61, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x64,
	0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x2e, 0x50, 0x75, 0x74, 0x4a, 0x69, 0x72, 0x61,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x52, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4a, 0x69, 0x72, 0x61, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x23, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73,
	0x69, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4a, 0x69, 0x72, 0x61, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0a, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x53,
	0x63, 0x61, 0x6e, 0x12, 0x1c, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x2e,
	0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x2e, 0x49, 0x6e,
	0x76, 0x6f, 0x6b, 0x65, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x41, 0x0a, 0x0d, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x53, 0x63, 0x61, 0x6e,
	0x41, 0x6c, 0x6c, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x79, 0x62, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x6d,
	0x69, 0x6d, 0x6f, 0x73, 0x61, 0x2d, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_diagnosis_services_proto_rawDescOnce sync.Once
	file_diagnosis_services_proto_rawDescData = file_diagnosis_services_proto_rawDesc
)

func file_diagnosis_services_proto_rawDescGZIP() []byte {
	file_diagnosis_services_proto_rawDescOnce.Do(func() {
		file_diagnosis_services_proto_rawDescData = protoimpl.X.CompressGZIP(file_diagnosis_services_proto_rawDescData)
	})
	return file_diagnosis_services_proto_rawDescData
}

var file_diagnosis_services_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_diagnosis_services_proto_goTypes = []interface{}{
	(*ListDiagnosisDataSourceRequest)(nil),   // 0: diagnosis.ListDiagnosisDataSourceRequest
	(*ListDiagnosisDataSourceResponse)(nil),  // 1: diagnosis.ListDiagnosisDataSourceResponse
	(*GetDiagnosisDataSourceRequest)(nil),    // 2: diagnosis.GetDiagnosisDataSourceRequest
	(*GetDiagnosisDataSourceResponse)(nil),   // 3: diagnosis.GetDiagnosisDataSourceResponse
	(*PutDiagnosisDataSourceRequest)(nil),    // 4: diagnosis.PutDiagnosisDataSourceRequest
	(*PutDiagnosisDataSourceResponse)(nil),   // 5: diagnosis.PutDiagnosisDataSourceResponse
	(*DeleteDiagnosisDataSourceRequest)(nil), // 6: diagnosis.DeleteDiagnosisDataSourceRequest
	(*ListJiraSettingRequest)(nil),           // 7: diagnosis.ListJiraSettingRequest
	(*ListJiraSettingResponse)(nil),          // 8: diagnosis.ListJiraSettingResponse
	(*GetJiraSettingRequest)(nil),            // 9: diagnosis.GetJiraSettingRequest
	(*GetJiraSettingResponse)(nil),           // 10: diagnosis.GetJiraSettingResponse
	(*PutJiraSettingRequest)(nil),            // 11: diagnosis.PutJiraSettingRequest
	(*PutJiraSettingResponse)(nil),           // 12: diagnosis.PutJiraSettingResponse
	(*DeleteJiraSettingRequest)(nil),         // 13: diagnosis.DeleteJiraSettingRequest
	(*InvokeScanRequest)(nil),                // 14: diagnosis.InvokeScanRequest
	(*InvokeScanResponse)(nil),               // 15: diagnosis.InvokeScanResponse
	(*DiagnosisDataSource)(nil),              // 16: diagnosis.DiagnosisDataSource
	(*DiagnosisDataSourceForUpsert)(nil),     // 17: diagnosis.DiagnosisDataSourceForUpsert
	(*JiraSetting)(nil),                      // 18: diagnosis.JiraSetting
	(*JiraSettingForUpsert)(nil),             // 19: diagnosis.JiraSettingForUpsert
	(*empty.Empty)(nil),                      // 20: google.protobuf.Empty
}
var file_diagnosis_services_proto_depIdxs = []int32{
	16, // 0: diagnosis.ListDiagnosisDataSourceResponse.diagnosis_data_source:type_name -> diagnosis.DiagnosisDataSource
	16, // 1: diagnosis.GetDiagnosisDataSourceResponse.diagnosis_data_source:type_name -> diagnosis.DiagnosisDataSource
	17, // 2: diagnosis.PutDiagnosisDataSourceRequest.diagnosis_data_source:type_name -> diagnosis.DiagnosisDataSourceForUpsert
	16, // 3: diagnosis.PutDiagnosisDataSourceResponse.diagnosis_data_source:type_name -> diagnosis.DiagnosisDataSource
	18, // 4: diagnosis.ListJiraSettingResponse.jira_setting:type_name -> diagnosis.JiraSetting
	18, // 5: diagnosis.GetJiraSettingResponse.jira_setting:type_name -> diagnosis.JiraSetting
	19, // 6: diagnosis.PutJiraSettingRequest.jira_setting:type_name -> diagnosis.JiraSettingForUpsert
	18, // 7: diagnosis.PutJiraSettingResponse.jira_setting:type_name -> diagnosis.JiraSetting
	0,  // 8: diagnosis.DiagnosisService.ListDiagnosisDataSource:input_type -> diagnosis.ListDiagnosisDataSourceRequest
	2,  // 9: diagnosis.DiagnosisService.GetDiagnosisDataSource:input_type -> diagnosis.GetDiagnosisDataSourceRequest
	4,  // 10: diagnosis.DiagnosisService.PutDiagnosisDataSource:input_type -> diagnosis.PutDiagnosisDataSourceRequest
	6,  // 11: diagnosis.DiagnosisService.DeleteDiagnosisDataSource:input_type -> diagnosis.DeleteDiagnosisDataSourceRequest
	7,  // 12: diagnosis.DiagnosisService.ListJiraSetting:input_type -> diagnosis.ListJiraSettingRequest
	9,  // 13: diagnosis.DiagnosisService.GetJiraSetting:input_type -> diagnosis.GetJiraSettingRequest
	11, // 14: diagnosis.DiagnosisService.PutJiraSetting:input_type -> diagnosis.PutJiraSettingRequest
	13, // 15: diagnosis.DiagnosisService.DeleteJiraSetting:input_type -> diagnosis.DeleteJiraSettingRequest
	14, // 16: diagnosis.DiagnosisService.InvokeScan:input_type -> diagnosis.InvokeScanRequest
	20, // 17: diagnosis.DiagnosisService.InvokeScanAll:input_type -> google.protobuf.Empty
	1,  // 18: diagnosis.DiagnosisService.ListDiagnosisDataSource:output_type -> diagnosis.ListDiagnosisDataSourceResponse
	3,  // 19: diagnosis.DiagnosisService.GetDiagnosisDataSource:output_type -> diagnosis.GetDiagnosisDataSourceResponse
	5,  // 20: diagnosis.DiagnosisService.PutDiagnosisDataSource:output_type -> diagnosis.PutDiagnosisDataSourceResponse
	20, // 21: diagnosis.DiagnosisService.DeleteDiagnosisDataSource:output_type -> google.protobuf.Empty
	8,  // 22: diagnosis.DiagnosisService.ListJiraSetting:output_type -> diagnosis.ListJiraSettingResponse
	10, // 23: diagnosis.DiagnosisService.GetJiraSetting:output_type -> diagnosis.GetJiraSettingResponse
	12, // 24: diagnosis.DiagnosisService.PutJiraSetting:output_type -> diagnosis.PutJiraSettingResponse
	20, // 25: diagnosis.DiagnosisService.DeleteJiraSetting:output_type -> google.protobuf.Empty
	15, // 26: diagnosis.DiagnosisService.InvokeScan:output_type -> diagnosis.InvokeScanResponse
	20, // 27: diagnosis.DiagnosisService.InvokeScanAll:output_type -> google.protobuf.Empty
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_diagnosis_services_proto_init() }
func file_diagnosis_services_proto_init() {
	if File_diagnosis_services_proto != nil {
		return
	}
	file_diagnosis_entities_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_diagnosis_services_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDiagnosisDataSourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diagnosis_services_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDiagnosisDataSourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diagnosis_services_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDiagnosisDataSourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diagnosis_services_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDiagnosisDataSourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diagnosis_services_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutDiagnosisDataSourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diagnosis_services_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutDiagnosisDataSourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diagnosis_services_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDiagnosisDataSourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diagnosis_services_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListJiraSettingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diagnosis_services_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListJiraSettingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diagnosis_services_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJiraSettingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diagnosis_services_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJiraSettingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diagnosis_services_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutJiraSettingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diagnosis_services_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutJiraSettingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diagnosis_services_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteJiraSettingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diagnosis_services_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvokeScanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diagnosis_services_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvokeScanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_diagnosis_services_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_diagnosis_services_proto_goTypes,
		DependencyIndexes: file_diagnosis_services_proto_depIdxs,
		MessageInfos:      file_diagnosis_services_proto_msgTypes,
	}.Build()
	File_diagnosis_services_proto = out.File
	file_diagnosis_services_proto_rawDesc = nil
	file_diagnosis_services_proto_goTypes = nil
	file_diagnosis_services_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DiagnosisServiceClient is the client API for DiagnosisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiagnosisServiceClient interface {
	// DataSource
	ListDiagnosisDataSource(ctx context.Context, in *ListDiagnosisDataSourceRequest, opts ...grpc.CallOption) (*ListDiagnosisDataSourceResponse, error)
	GetDiagnosisDataSource(ctx context.Context, in *GetDiagnosisDataSourceRequest, opts ...grpc.CallOption) (*GetDiagnosisDataSourceResponse, error)
	PutDiagnosisDataSource(ctx context.Context, in *PutDiagnosisDataSourceRequest, opts ...grpc.CallOption) (*PutDiagnosisDataSourceResponse, error)
	DeleteDiagnosisDataSource(ctx context.Context, in *DeleteDiagnosisDataSourceRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// JiraSetting
	ListJiraSetting(ctx context.Context, in *ListJiraSettingRequest, opts ...grpc.CallOption) (*ListJiraSettingResponse, error)
	GetJiraSetting(ctx context.Context, in *GetJiraSettingRequest, opts ...grpc.CallOption) (*GetJiraSettingResponse, error)
	PutJiraSetting(ctx context.Context, in *PutJiraSettingRequest, opts ...grpc.CallOption) (*PutJiraSettingResponse, error)
	DeleteJiraSetting(ctx context.Context, in *DeleteJiraSettingRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// KICK
	InvokeScan(ctx context.Context, in *InvokeScanRequest, opts ...grpc.CallOption) (*InvokeScanResponse, error)
	InvokeScanAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type diagnosisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiagnosisServiceClient(cc grpc.ClientConnInterface) DiagnosisServiceClient {
	return &diagnosisServiceClient{cc}
}

func (c *diagnosisServiceClient) ListDiagnosisDataSource(ctx context.Context, in *ListDiagnosisDataSourceRequest, opts ...grpc.CallOption) (*ListDiagnosisDataSourceResponse, error) {
	out := new(ListDiagnosisDataSourceResponse)
	err := c.cc.Invoke(ctx, "/diagnosis.DiagnosisService/ListDiagnosisDataSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosisServiceClient) GetDiagnosisDataSource(ctx context.Context, in *GetDiagnosisDataSourceRequest, opts ...grpc.CallOption) (*GetDiagnosisDataSourceResponse, error) {
	out := new(GetDiagnosisDataSourceResponse)
	err := c.cc.Invoke(ctx, "/diagnosis.DiagnosisService/GetDiagnosisDataSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosisServiceClient) PutDiagnosisDataSource(ctx context.Context, in *PutDiagnosisDataSourceRequest, opts ...grpc.CallOption) (*PutDiagnosisDataSourceResponse, error) {
	out := new(PutDiagnosisDataSourceResponse)
	err := c.cc.Invoke(ctx, "/diagnosis.DiagnosisService/PutDiagnosisDataSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosisServiceClient) DeleteDiagnosisDataSource(ctx context.Context, in *DeleteDiagnosisDataSourceRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/diagnosis.DiagnosisService/DeleteDiagnosisDataSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosisServiceClient) ListJiraSetting(ctx context.Context, in *ListJiraSettingRequest, opts ...grpc.CallOption) (*ListJiraSettingResponse, error) {
	out := new(ListJiraSettingResponse)
	err := c.cc.Invoke(ctx, "/diagnosis.DiagnosisService/ListJiraSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosisServiceClient) GetJiraSetting(ctx context.Context, in *GetJiraSettingRequest, opts ...grpc.CallOption) (*GetJiraSettingResponse, error) {
	out := new(GetJiraSettingResponse)
	err := c.cc.Invoke(ctx, "/diagnosis.DiagnosisService/GetJiraSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosisServiceClient) PutJiraSetting(ctx context.Context, in *PutJiraSettingRequest, opts ...grpc.CallOption) (*PutJiraSettingResponse, error) {
	out := new(PutJiraSettingResponse)
	err := c.cc.Invoke(ctx, "/diagnosis.DiagnosisService/PutJiraSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosisServiceClient) DeleteJiraSetting(ctx context.Context, in *DeleteJiraSettingRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/diagnosis.DiagnosisService/DeleteJiraSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosisServiceClient) InvokeScan(ctx context.Context, in *InvokeScanRequest, opts ...grpc.CallOption) (*InvokeScanResponse, error) {
	out := new(InvokeScanResponse)
	err := c.cc.Invoke(ctx, "/diagnosis.DiagnosisService/InvokeScan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosisServiceClient) InvokeScanAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/diagnosis.DiagnosisService/InvokeScanAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiagnosisServiceServer is the server API for DiagnosisService service.
type DiagnosisServiceServer interface {
	// DataSource
	ListDiagnosisDataSource(context.Context, *ListDiagnosisDataSourceRequest) (*ListDiagnosisDataSourceResponse, error)
	GetDiagnosisDataSource(context.Context, *GetDiagnosisDataSourceRequest) (*GetDiagnosisDataSourceResponse, error)
	PutDiagnosisDataSource(context.Context, *PutDiagnosisDataSourceRequest) (*PutDiagnosisDataSourceResponse, error)
	DeleteDiagnosisDataSource(context.Context, *DeleteDiagnosisDataSourceRequest) (*empty.Empty, error)
	// JiraSetting
	ListJiraSetting(context.Context, *ListJiraSettingRequest) (*ListJiraSettingResponse, error)
	GetJiraSetting(context.Context, *GetJiraSettingRequest) (*GetJiraSettingResponse, error)
	PutJiraSetting(context.Context, *PutJiraSettingRequest) (*PutJiraSettingResponse, error)
	DeleteJiraSetting(context.Context, *DeleteJiraSettingRequest) (*empty.Empty, error)
	// KICK
	InvokeScan(context.Context, *InvokeScanRequest) (*InvokeScanResponse, error)
	InvokeScanAll(context.Context, *empty.Empty) (*empty.Empty, error)
}

// UnimplementedDiagnosisServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDiagnosisServiceServer struct {
}

func (*UnimplementedDiagnosisServiceServer) ListDiagnosisDataSource(context.Context, *ListDiagnosisDataSourceRequest) (*ListDiagnosisDataSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDiagnosisDataSource not implemented")
}
func (*UnimplementedDiagnosisServiceServer) GetDiagnosisDataSource(context.Context, *GetDiagnosisDataSourceRequest) (*GetDiagnosisDataSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiagnosisDataSource not implemented")
}
func (*UnimplementedDiagnosisServiceServer) PutDiagnosisDataSource(context.Context, *PutDiagnosisDataSourceRequest) (*PutDiagnosisDataSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutDiagnosisDataSource not implemented")
}
func (*UnimplementedDiagnosisServiceServer) DeleteDiagnosisDataSource(context.Context, *DeleteDiagnosisDataSourceRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDiagnosisDataSource not implemented")
}
func (*UnimplementedDiagnosisServiceServer) ListJiraSetting(context.Context, *ListJiraSettingRequest) (*ListJiraSettingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListJiraSetting not implemented")
}
func (*UnimplementedDiagnosisServiceServer) GetJiraSetting(context.Context, *GetJiraSettingRequest) (*GetJiraSettingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJiraSetting not implemented")
}
func (*UnimplementedDiagnosisServiceServer) PutJiraSetting(context.Context, *PutJiraSettingRequest) (*PutJiraSettingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutJiraSetting not implemented")
}
func (*UnimplementedDiagnosisServiceServer) DeleteJiraSetting(context.Context, *DeleteJiraSettingRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteJiraSetting not implemented")
}
func (*UnimplementedDiagnosisServiceServer) InvokeScan(context.Context, *InvokeScanRequest) (*InvokeScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeScan not implemented")
}
func (*UnimplementedDiagnosisServiceServer) InvokeScanAll(context.Context, *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeScanAll not implemented")
}

func RegisterDiagnosisServiceServer(s *grpc.Server, srv DiagnosisServiceServer) {
	s.RegisterService(&_DiagnosisService_serviceDesc, srv)
}

func _DiagnosisService_ListDiagnosisDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDiagnosisDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServiceServer).ListDiagnosisDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diagnosis.DiagnosisService/ListDiagnosisDataSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServiceServer).ListDiagnosisDataSource(ctx, req.(*ListDiagnosisDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagnosisService_GetDiagnosisDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiagnosisDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServiceServer).GetDiagnosisDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diagnosis.DiagnosisService/GetDiagnosisDataSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServiceServer).GetDiagnosisDataSource(ctx, req.(*GetDiagnosisDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagnosisService_PutDiagnosisDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutDiagnosisDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServiceServer).PutDiagnosisDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diagnosis.DiagnosisService/PutDiagnosisDataSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServiceServer).PutDiagnosisDataSource(ctx, req.(*PutDiagnosisDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagnosisService_DeleteDiagnosisDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDiagnosisDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServiceServer).DeleteDiagnosisDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diagnosis.DiagnosisService/DeleteDiagnosisDataSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServiceServer).DeleteDiagnosisDataSource(ctx, req.(*DeleteDiagnosisDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagnosisService_ListJiraSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJiraSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServiceServer).ListJiraSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diagnosis.DiagnosisService/ListJiraSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServiceServer).ListJiraSetting(ctx, req.(*ListJiraSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagnosisService_GetJiraSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJiraSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServiceServer).GetJiraSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diagnosis.DiagnosisService/GetJiraSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServiceServer).GetJiraSetting(ctx, req.(*GetJiraSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagnosisService_PutJiraSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutJiraSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServiceServer).PutJiraSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diagnosis.DiagnosisService/PutJiraSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServiceServer).PutJiraSetting(ctx, req.(*PutJiraSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagnosisService_DeleteJiraSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJiraSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServiceServer).DeleteJiraSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diagnosis.DiagnosisService/DeleteJiraSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServiceServer).DeleteJiraSetting(ctx, req.(*DeleteJiraSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagnosisService_InvokeScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServiceServer).InvokeScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diagnosis.DiagnosisService/InvokeScan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServiceServer).InvokeScan(ctx, req.(*InvokeScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagnosisService_InvokeScanAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServiceServer).InvokeScanAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diagnosis.DiagnosisService/InvokeScanAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServiceServer).InvokeScanAll(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _DiagnosisService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "diagnosis.DiagnosisService",
	HandlerType: (*DiagnosisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDiagnosisDataSource",
			Handler:    _DiagnosisService_ListDiagnosisDataSource_Handler,
		},
		{
			MethodName: "GetDiagnosisDataSource",
			Handler:    _DiagnosisService_GetDiagnosisDataSource_Handler,
		},
		{
			MethodName: "PutDiagnosisDataSource",
			Handler:    _DiagnosisService_PutDiagnosisDataSource_Handler,
		},
		{
			MethodName: "DeleteDiagnosisDataSource",
			Handler:    _DiagnosisService_DeleteDiagnosisDataSource_Handler,
		},
		{
			MethodName: "ListJiraSetting",
			Handler:    _DiagnosisService_ListJiraSetting_Handler,
		},
		{
			MethodName: "GetJiraSetting",
			Handler:    _DiagnosisService_GetJiraSetting_Handler,
		},
		{
			MethodName: "PutJiraSetting",
			Handler:    _DiagnosisService_PutJiraSetting_Handler,
		},
		{
			MethodName: "DeleteJiraSetting",
			Handler:    _DiagnosisService_DeleteJiraSetting_Handler,
		},
		{
			MethodName: "InvokeScan",
			Handler:    _DiagnosisService_InvokeScan_Handler,
		},
		{
			MethodName: "InvokeScanAll",
			Handler:    _DiagnosisService_InvokeScanAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "diagnosis/services.proto",
}
