// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entities.proto

package diagnosis

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Diagnosis struct {
	DiagnosisId          uint32   `protobuf:"varint,1,opt,name=diagnosis_id,json=diagnosisId,proto3" json:"diagnosis_id,omitempty"`
	ProjectId            uint32   `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            int64    `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Diagnosis) Reset()         { *m = Diagnosis{} }
func (m *Diagnosis) String() string { return proto.CompactTextString(m) }
func (*Diagnosis) ProtoMessage()    {}
func (*Diagnosis) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{0}
}

func (m *Diagnosis) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Diagnosis.Unmarshal(m, b)
}
func (m *Diagnosis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Diagnosis.Marshal(b, m, deterministic)
}
func (m *Diagnosis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Diagnosis.Merge(m, src)
}
func (m *Diagnosis) XXX_Size() int {
	return xxx_messageInfo_Diagnosis.Size(m)
}
func (m *Diagnosis) XXX_DiscardUnknown() {
	xxx_messageInfo_Diagnosis.DiscardUnknown(m)
}

var xxx_messageInfo_Diagnosis proto.InternalMessageInfo

func (m *Diagnosis) GetDiagnosisId() uint32 {
	if m != nil {
		return m.DiagnosisId
	}
	return 0
}

func (m *Diagnosis) GetProjectId() uint32 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *Diagnosis) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Diagnosis) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Diagnosis) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type DiagnosisForUpsert struct {
	DiagnosisId          uint32   `protobuf:"varint,1,opt,name=diagnosis_id,json=diagnosisId,proto3" json:"diagnosis_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiagnosisForUpsert) Reset()         { *m = DiagnosisForUpsert{} }
func (m *DiagnosisForUpsert) String() string { return proto.CompactTextString(m) }
func (*DiagnosisForUpsert) ProtoMessage()    {}
func (*DiagnosisForUpsert) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{1}
}

func (m *DiagnosisForUpsert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiagnosisForUpsert.Unmarshal(m, b)
}
func (m *DiagnosisForUpsert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiagnosisForUpsert.Marshal(b, m, deterministic)
}
func (m *DiagnosisForUpsert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiagnosisForUpsert.Merge(m, src)
}
func (m *DiagnosisForUpsert) XXX_Size() int {
	return xxx_messageInfo_DiagnosisForUpsert.Size(m)
}
func (m *DiagnosisForUpsert) XXX_DiscardUnknown() {
	xxx_messageInfo_DiagnosisForUpsert.DiscardUnknown(m)
}

var xxx_messageInfo_DiagnosisForUpsert proto.InternalMessageInfo

func (m *DiagnosisForUpsert) GetDiagnosisId() uint32 {
	if m != nil {
		return m.DiagnosisId
	}
	return 0
}

func (m *DiagnosisForUpsert) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DiagnosisDataSource struct {
	DiagnosisDataSourceId uint32   `protobuf:"varint,1,opt,name=diagnosis_data_source_id,json=diagnosisDataSourceId,proto3" json:"diagnosis_data_source_id,omitempty"`
	Name                  string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description           string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MaxScore              float32  `protobuf:"fixed32,4,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	CreatedAt             int64    `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             int64    `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *DiagnosisDataSource) Reset()         { *m = DiagnosisDataSource{} }
func (m *DiagnosisDataSource) String() string { return proto.CompactTextString(m) }
func (*DiagnosisDataSource) ProtoMessage()    {}
func (*DiagnosisDataSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{2}
}

func (m *DiagnosisDataSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiagnosisDataSource.Unmarshal(m, b)
}
func (m *DiagnosisDataSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiagnosisDataSource.Marshal(b, m, deterministic)
}
func (m *DiagnosisDataSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiagnosisDataSource.Merge(m, src)
}
func (m *DiagnosisDataSource) XXX_Size() int {
	return xxx_messageInfo_DiagnosisDataSource.Size(m)
}
func (m *DiagnosisDataSource) XXX_DiscardUnknown() {
	xxx_messageInfo_DiagnosisDataSource.DiscardUnknown(m)
}

var xxx_messageInfo_DiagnosisDataSource proto.InternalMessageInfo

func (m *DiagnosisDataSource) GetDiagnosisDataSourceId() uint32 {
	if m != nil {
		return m.DiagnosisDataSourceId
	}
	return 0
}

func (m *DiagnosisDataSource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DiagnosisDataSource) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DiagnosisDataSource) GetMaxScore() float32 {
	if m != nil {
		return m.MaxScore
	}
	return 0
}

func (m *DiagnosisDataSource) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *DiagnosisDataSource) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type DiagnosisDataSourceForUpsert struct {
	DiagnosisDataSourceId uint32   `protobuf:"varint,1,opt,name=diagnosis_data_source_id,json=diagnosisDataSourceId,proto3" json:"diagnosis_data_source_id,omitempty"`
	Name                  string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description           string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MaxScore              float32  `protobuf:"fixed32,4,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *DiagnosisDataSourceForUpsert) Reset()         { *m = DiagnosisDataSourceForUpsert{} }
func (m *DiagnosisDataSourceForUpsert) String() string { return proto.CompactTextString(m) }
func (*DiagnosisDataSourceForUpsert) ProtoMessage()    {}
func (*DiagnosisDataSourceForUpsert) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{3}
}

func (m *DiagnosisDataSourceForUpsert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiagnosisDataSourceForUpsert.Unmarshal(m, b)
}
func (m *DiagnosisDataSourceForUpsert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiagnosisDataSourceForUpsert.Marshal(b, m, deterministic)
}
func (m *DiagnosisDataSourceForUpsert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiagnosisDataSourceForUpsert.Merge(m, src)
}
func (m *DiagnosisDataSourceForUpsert) XXX_Size() int {
	return xxx_messageInfo_DiagnosisDataSourceForUpsert.Size(m)
}
func (m *DiagnosisDataSourceForUpsert) XXX_DiscardUnknown() {
	xxx_messageInfo_DiagnosisDataSourceForUpsert.DiscardUnknown(m)
}

var xxx_messageInfo_DiagnosisDataSourceForUpsert proto.InternalMessageInfo

func (m *DiagnosisDataSourceForUpsert) GetDiagnosisDataSourceId() uint32 {
	if m != nil {
		return m.DiagnosisDataSourceId
	}
	return 0
}

func (m *DiagnosisDataSourceForUpsert) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DiagnosisDataSourceForUpsert) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DiagnosisDataSourceForUpsert) GetMaxScore() float32 {
	if m != nil {
		return m.MaxScore
	}
	return 0
}

type RelDiagnosisDataSource struct {
	RelDiagnosisDataSourceId uint32   `protobuf:"varint,1,opt,name=rel_diagnosis_data_source_id,json=relDiagnosisDataSourceId,proto3" json:"rel_diagnosis_data_source_id,omitempty"`
	DiagnosisDataSourceId    uint32   `protobuf:"varint,2,opt,name=diagnosis_data_source_id,json=diagnosisDataSourceId,proto3" json:"diagnosis_data_source_id,omitempty"`
	DiagnosisId              uint32   `protobuf:"varint,3,opt,name=diagnosis_id,json=diagnosisId,proto3" json:"diagnosis_id,omitempty"`
	ProjectId                uint32   `protobuf:"varint,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	RecordId                 string   `protobuf:"bytes,5,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	JiraId                   string   `protobuf:"bytes,6,opt,name=jira_id,json=jiraId,proto3" json:"jira_id,omitempty"`
	JiraKey                  string   `protobuf:"bytes,7,opt,name=jira_key,json=jiraKey,proto3" json:"jira_key,omitempty"`
	CreatedAt                int64    `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                int64    `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *RelDiagnosisDataSource) Reset()         { *m = RelDiagnosisDataSource{} }
func (m *RelDiagnosisDataSource) String() string { return proto.CompactTextString(m) }
func (*RelDiagnosisDataSource) ProtoMessage()    {}
func (*RelDiagnosisDataSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{4}
}

func (m *RelDiagnosisDataSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelDiagnosisDataSource.Unmarshal(m, b)
}
func (m *RelDiagnosisDataSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelDiagnosisDataSource.Marshal(b, m, deterministic)
}
func (m *RelDiagnosisDataSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelDiagnosisDataSource.Merge(m, src)
}
func (m *RelDiagnosisDataSource) XXX_Size() int {
	return xxx_messageInfo_RelDiagnosisDataSource.Size(m)
}
func (m *RelDiagnosisDataSource) XXX_DiscardUnknown() {
	xxx_messageInfo_RelDiagnosisDataSource.DiscardUnknown(m)
}

var xxx_messageInfo_RelDiagnosisDataSource proto.InternalMessageInfo

func (m *RelDiagnosisDataSource) GetRelDiagnosisDataSourceId() uint32 {
	if m != nil {
		return m.RelDiagnosisDataSourceId
	}
	return 0
}

func (m *RelDiagnosisDataSource) GetDiagnosisDataSourceId() uint32 {
	if m != nil {
		return m.DiagnosisDataSourceId
	}
	return 0
}

func (m *RelDiagnosisDataSource) GetDiagnosisId() uint32 {
	if m != nil {
		return m.DiagnosisId
	}
	return 0
}

func (m *RelDiagnosisDataSource) GetProjectId() uint32 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *RelDiagnosisDataSource) GetRecordId() string {
	if m != nil {
		return m.RecordId
	}
	return ""
}

func (m *RelDiagnosisDataSource) GetJiraId() string {
	if m != nil {
		return m.JiraId
	}
	return ""
}

func (m *RelDiagnosisDataSource) GetJiraKey() string {
	if m != nil {
		return m.JiraKey
	}
	return ""
}

func (m *RelDiagnosisDataSource) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *RelDiagnosisDataSource) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type RelDiagnosisDataSourceForUpsert struct {
	RelDiagnosisDataSourceId uint32   `protobuf:"varint,1,opt,name=rel_diagnosis_data_source_id,json=relDiagnosisDataSourceId,proto3" json:"rel_diagnosis_data_source_id,omitempty"`
	DiagnosisDataSourceId    uint32   `protobuf:"varint,2,opt,name=diagnosis_data_source_id,json=diagnosisDataSourceId,proto3" json:"diagnosis_data_source_id,omitempty"`
	DiagnosisId              uint32   `protobuf:"varint,3,opt,name=diagnosis_id,json=diagnosisId,proto3" json:"diagnosis_id,omitempty"`
	RecordId                 string   `protobuf:"bytes,4,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	JiraId                   string   `protobuf:"bytes,5,opt,name=jira_id,json=jiraId,proto3" json:"jira_id,omitempty"`
	JiraKey                  string   `protobuf:"bytes,6,opt,name=jira_key,json=jiraKey,proto3" json:"jira_key,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *RelDiagnosisDataSourceForUpsert) Reset()         { *m = RelDiagnosisDataSourceForUpsert{} }
func (m *RelDiagnosisDataSourceForUpsert) String() string { return proto.CompactTextString(m) }
func (*RelDiagnosisDataSourceForUpsert) ProtoMessage()    {}
func (*RelDiagnosisDataSourceForUpsert) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{5}
}

func (m *RelDiagnosisDataSourceForUpsert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelDiagnosisDataSourceForUpsert.Unmarshal(m, b)
}
func (m *RelDiagnosisDataSourceForUpsert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelDiagnosisDataSourceForUpsert.Marshal(b, m, deterministic)
}
func (m *RelDiagnosisDataSourceForUpsert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelDiagnosisDataSourceForUpsert.Merge(m, src)
}
func (m *RelDiagnosisDataSourceForUpsert) XXX_Size() int {
	return xxx_messageInfo_RelDiagnosisDataSourceForUpsert.Size(m)
}
func (m *RelDiagnosisDataSourceForUpsert) XXX_DiscardUnknown() {
	xxx_messageInfo_RelDiagnosisDataSourceForUpsert.DiscardUnknown(m)
}

var xxx_messageInfo_RelDiagnosisDataSourceForUpsert proto.InternalMessageInfo

func (m *RelDiagnosisDataSourceForUpsert) GetRelDiagnosisDataSourceId() uint32 {
	if m != nil {
		return m.RelDiagnosisDataSourceId
	}
	return 0
}

func (m *RelDiagnosisDataSourceForUpsert) GetDiagnosisDataSourceId() uint32 {
	if m != nil {
		return m.DiagnosisDataSourceId
	}
	return 0
}

func (m *RelDiagnosisDataSourceForUpsert) GetDiagnosisId() uint32 {
	if m != nil {
		return m.DiagnosisId
	}
	return 0
}

func (m *RelDiagnosisDataSourceForUpsert) GetRecordId() string {
	if m != nil {
		return m.RecordId
	}
	return ""
}

func (m *RelDiagnosisDataSourceForUpsert) GetJiraId() string {
	if m != nil {
		return m.JiraId
	}
	return ""
}

func (m *RelDiagnosisDataSourceForUpsert) GetJiraKey() string {
	if m != nil {
		return m.JiraKey
	}
	return ""
}

func init() {
	proto.RegisterType((*Diagnosis)(nil), "diagnosis.Diagnosis")
	proto.RegisterType((*DiagnosisForUpsert)(nil), "diagnosis.DiagnosisForUpsert")
	proto.RegisterType((*DiagnosisDataSource)(nil), "diagnosis.DiagnosisDataSource")
	proto.RegisterType((*DiagnosisDataSourceForUpsert)(nil), "diagnosis.DiagnosisDataSourceForUpsert")
	proto.RegisterType((*RelDiagnosisDataSource)(nil), "diagnosis.RelDiagnosisDataSource")
	proto.RegisterType((*RelDiagnosisDataSourceForUpsert)(nil), "diagnosis.RelDiagnosisDataSourceForUpsert")
}

func init() { proto.RegisterFile("entities.proto", fileDescriptor_a5f7344b79fcc63d) }

var fileDescriptor_a5f7344b79fcc63d = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0x86, 0x95, 0xec, 0x6e, 0xba, 0x9e, 0x02, 0x07, 0x23, 0x20, 0xa8, 0x45, 0x84, 0x9c, 0xf6,
	0x42, 0x73, 0xe0, 0x50, 0x71, 0x41, 0x5a, 0xa8, 0x90, 0xa2, 0xde, 0x52, 0x71, 0xe1, 0x12, 0x39,
	0xf1, 0x28, 0xb8, 0x6d, 0xe2, 0xc8, 0xf6, 0x4a, 0xdd, 0x97, 0xe0, 0x15, 0xb8, 0xf3, 0x52, 0x48,
	0x3c, 0x09, 0x8a, 0x9b, 0x4d, 0x68, 0x48, 0x53, 0x8e, 0x7b, 0x5b, 0xff, 0xff, 0xcc, 0x78, 0xe6,
	0xdb, 0x71, 0xe0, 0x09, 0x56, 0x46, 0x18, 0x81, 0xfa, 0xa4, 0x56, 0xd2, 0x48, 0x4a, 0xb8, 0x60,
	0x45, 0x25, 0xb5, 0xd0, 0xe1, 0x0f, 0x07, 0xc8, 0xd9, 0xee, 0x44, 0xdf, 0xc0, 0xa3, 0xce, 0x4a,
	0x05, 0xf7, 0x9d, 0xc0, 0x59, 0x3d, 0x4e, 0x0e, 0x3b, 0x2d, 0xe6, 0xf4, 0x15, 0x40, 0xad, 0xe4,
	0x25, 0xe6, 0xa6, 0x09, 0x70, 0x6d, 0x00, 0x69, 0x95, 0x98, 0x53, 0x0a, 0xf3, 0x8a, 0x95, 0xe8,
	0xcf, 0x02, 0x67, 0x45, 0x12, 0xfb, 0xbb, 0x49, 0xc9, 0x15, 0x32, 0x83, 0x3c, 0x65, 0xc6, 0x9f,
	0x07, 0xce, 0x6a, 0x96, 0x90, 0x56, 0x59, 0x9b, 0xc6, 0xde, 0xd4, 0x7c, 0x67, 0x2f, 0x6e, 0xed,
	0x56, 0x59, 0x9b, 0xf0, 0x1c, 0x68, 0xd7, 0xe0, 0x67, 0xa9, 0xbe, 0xd4, 0x1a, 0x95, 0xf9, 0x9f,
	0x4e, 0x77, 0xad, 0xb8, 0x7d, 0x2b, 0xe1, 0x2f, 0x07, 0x9e, 0x76, 0xd5, 0xce, 0x98, 0x61, 0x17,
	0x72, 0xa3, 0x72, 0xa4, 0xa7, 0xe0, 0xf7, 0xe5, 0x38, 0x33, 0x2c, 0xd5, 0xd6, 0xe8, 0x4b, 0x3f,
	0xe3, 0xff, 0xa6, 0x8d, 0x5f, 0x42, 0x03, 0x38, 0xe4, 0xa8, 0x73, 0x25, 0x6a, 0x23, 0x64, 0xd5,
	0xa2, 0xf8, 0x5b, 0xa2, 0x47, 0x40, 0x4a, 0x76, 0x93, 0xea, 0x5c, 0x2a, 0xb4, 0x40, 0xdc, 0x64,
	0x59, 0xb2, 0x9b, 0x8b, 0xe6, 0x3c, 0xc0, 0xb5, 0x98, 0xc6, 0xe5, 0x0d, 0x71, 0xfd, 0x74, 0xe0,
	0x78, 0x64, 0xc2, 0x9e, 0xdc, 0x1e, 0x8d, 0x1a, 0xfe, 0x76, 0xe1, 0x79, 0x82, 0xd7, 0x63, 0xff,
	0xc8, 0x07, 0x38, 0x56, 0x78, 0x9d, 0x3e, 0xd0, 0xaa, 0xaf, 0x46, 0xb3, 0x63, 0x3e, 0x39, 0xa6,
	0x3b, 0x35, 0xe6, 0x70, 0xb3, 0x66, 0x0f, 0xbd, 0x81, 0xf9, 0xf0, 0x0d, 0x1c, 0x01, 0x51, 0x98,
	0x4b, 0xc5, 0x1b, 0x77, 0x61, 0x91, 0x2c, 0x6f, 0x85, 0x98, 0xd3, 0x17, 0x70, 0x70, 0x29, 0x14,
	0x6b, 0x2c, 0xcf, 0x5a, 0x5e, 0x73, 0x8c, 0x39, 0x7d, 0x09, 0x4b, 0x6b, 0x5c, 0xe1, 0xd6, 0x3f,
	0xb0, 0x8e, 0x0d, 0x3c, 0xc7, 0xed, 0x60, 0x23, 0x96, 0xd3, 0x1b, 0x41, 0x86, 0x1b, 0xf1, 0xdd,
	0x85, 0xd7, 0xe3, 0x90, 0xfb, 0xa5, 0xd8, 0x67, 0xda, 0x77, 0x70, 0xce, 0xef, 0xc7, 0xb9, 0xb8,
	0x17, 0xa7, 0x77, 0x07, 0xe7, 0xc7, 0xf7, 0x5f, 0x4f, 0x0b, 0x61, 0xbe, 0x6d, 0xb2, 0x93, 0x5c,
	0x96, 0xd1, 0xa7, 0x6d, 0x86, 0x6a, 0x5d, 0x60, 0x65, 0xa2, 0x52, 0x94, 0x52, 0xb3, 0xb7, 0xdd,
	0xe5, 0x51, 0x7d, 0x55, 0x44, 0x75, 0x16, 0x75, 0x42, 0xe6, 0xd9, 0x0f, 0xe8, 0xbb, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xa4, 0xf0, 0xaa, 0x3e, 0x52, 0x05, 0x00, 0x00,
}
