// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entities.proto

package diagnosis

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Diagnosis struct {
	DiagnosisId          uint64   `protobuf:"varint,1,opt,name=diagnosis_id,json=diagnosisId,proto3" json:"diagnosis_id,omitempty"`
	ProjectId            uint64   `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            int64    `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Diagnosis) Reset()         { *m = Diagnosis{} }
func (m *Diagnosis) String() string { return proto.CompactTextString(m) }
func (*Diagnosis) ProtoMessage()    {}
func (*Diagnosis) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{0}
}

func (m *Diagnosis) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Diagnosis.Unmarshal(m, b)
}
func (m *Diagnosis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Diagnosis.Marshal(b, m, deterministic)
}
func (m *Diagnosis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Diagnosis.Merge(m, src)
}
func (m *Diagnosis) XXX_Size() int {
	return xxx_messageInfo_Diagnosis.Size(m)
}
func (m *Diagnosis) XXX_DiscardUnknown() {
	xxx_messageInfo_Diagnosis.DiscardUnknown(m)
}

var xxx_messageInfo_Diagnosis proto.InternalMessageInfo

func (m *Diagnosis) GetDiagnosisId() uint64 {
	if m != nil {
		return m.DiagnosisId
	}
	return 0
}

func (m *Diagnosis) GetProjectId() uint64 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *Diagnosis) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Diagnosis) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Diagnosis) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type DiagnosisForUpsert struct {
	DiagnosisId          uint64   `protobuf:"varint,1,opt,name=diagnosis_id,json=diagnosisId,proto3" json:"diagnosis_id,omitempty"`
	ProjectId            uint64   `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiagnosisForUpsert) Reset()         { *m = DiagnosisForUpsert{} }
func (m *DiagnosisForUpsert) String() string { return proto.CompactTextString(m) }
func (*DiagnosisForUpsert) ProtoMessage()    {}
func (*DiagnosisForUpsert) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{1}
}

func (m *DiagnosisForUpsert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiagnosisForUpsert.Unmarshal(m, b)
}
func (m *DiagnosisForUpsert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiagnosisForUpsert.Marshal(b, m, deterministic)
}
func (m *DiagnosisForUpsert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiagnosisForUpsert.Merge(m, src)
}
func (m *DiagnosisForUpsert) XXX_Size() int {
	return xxx_messageInfo_DiagnosisForUpsert.Size(m)
}
func (m *DiagnosisForUpsert) XXX_DiscardUnknown() {
	xxx_messageInfo_DiagnosisForUpsert.DiscardUnknown(m)
}

var xxx_messageInfo_DiagnosisForUpsert proto.InternalMessageInfo

func (m *DiagnosisForUpsert) GetDiagnosisId() uint64 {
	if m != nil {
		return m.DiagnosisId
	}
	return 0
}

func (m *DiagnosisForUpsert) GetProjectId() uint64 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *DiagnosisForUpsert) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DiagnosisDataSource struct {
	DiagnosisDataSourceId uint64   `protobuf:"varint,1,opt,name=diagnosis_data_source_id,json=diagnosisDataSourceId,proto3" json:"diagnosis_data_source_id,omitempty"`
	Name                  string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description           string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MaxScore              float32  `protobuf:"fixed32,4,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	CreatedAt             int64    `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             int64    `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *DiagnosisDataSource) Reset()         { *m = DiagnosisDataSource{} }
func (m *DiagnosisDataSource) String() string { return proto.CompactTextString(m) }
func (*DiagnosisDataSource) ProtoMessage()    {}
func (*DiagnosisDataSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{2}
}

func (m *DiagnosisDataSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiagnosisDataSource.Unmarshal(m, b)
}
func (m *DiagnosisDataSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiagnosisDataSource.Marshal(b, m, deterministic)
}
func (m *DiagnosisDataSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiagnosisDataSource.Merge(m, src)
}
func (m *DiagnosisDataSource) XXX_Size() int {
	return xxx_messageInfo_DiagnosisDataSource.Size(m)
}
func (m *DiagnosisDataSource) XXX_DiscardUnknown() {
	xxx_messageInfo_DiagnosisDataSource.DiscardUnknown(m)
}

var xxx_messageInfo_DiagnosisDataSource proto.InternalMessageInfo

func (m *DiagnosisDataSource) GetDiagnosisDataSourceId() uint64 {
	if m != nil {
		return m.DiagnosisDataSourceId
	}
	return 0
}

func (m *DiagnosisDataSource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DiagnosisDataSource) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DiagnosisDataSource) GetMaxScore() float32 {
	if m != nil {
		return m.MaxScore
	}
	return 0
}

func (m *DiagnosisDataSource) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *DiagnosisDataSource) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type DiagnosisDataSourceForUpsert struct {
	DiagnosisDataSourceId uint64   `protobuf:"varint,1,opt,name=diagnosis_data_source_id,json=diagnosisDataSourceId,proto3" json:"diagnosis_data_source_id,omitempty"`
	Name                  string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description           string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MaxScore              float32  `protobuf:"fixed32,4,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *DiagnosisDataSourceForUpsert) Reset()         { *m = DiagnosisDataSourceForUpsert{} }
func (m *DiagnosisDataSourceForUpsert) String() string { return proto.CompactTextString(m) }
func (*DiagnosisDataSourceForUpsert) ProtoMessage()    {}
func (*DiagnosisDataSourceForUpsert) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{3}
}

func (m *DiagnosisDataSourceForUpsert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiagnosisDataSourceForUpsert.Unmarshal(m, b)
}
func (m *DiagnosisDataSourceForUpsert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiagnosisDataSourceForUpsert.Marshal(b, m, deterministic)
}
func (m *DiagnosisDataSourceForUpsert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiagnosisDataSourceForUpsert.Merge(m, src)
}
func (m *DiagnosisDataSourceForUpsert) XXX_Size() int {
	return xxx_messageInfo_DiagnosisDataSourceForUpsert.Size(m)
}
func (m *DiagnosisDataSourceForUpsert) XXX_DiscardUnknown() {
	xxx_messageInfo_DiagnosisDataSourceForUpsert.DiscardUnknown(m)
}

var xxx_messageInfo_DiagnosisDataSourceForUpsert proto.InternalMessageInfo

func (m *DiagnosisDataSourceForUpsert) GetDiagnosisDataSourceId() uint64 {
	if m != nil {
		return m.DiagnosisDataSourceId
	}
	return 0
}

func (m *DiagnosisDataSourceForUpsert) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DiagnosisDataSourceForUpsert) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DiagnosisDataSourceForUpsert) GetMaxScore() float32 {
	if m != nil {
		return m.MaxScore
	}
	return 0
}

type RelDiagnosisDataSource struct {
	RelDiagnosisDataSourceId uint64   `protobuf:"varint,1,opt,name=rel_diagnosis_data_source_id,json=relDiagnosisDataSourceId,proto3" json:"rel_diagnosis_data_source_id,omitempty"`
	DiagnosisDataSourceId    uint64   `protobuf:"varint,2,opt,name=diagnosis_data_source_id,json=diagnosisDataSourceId,proto3" json:"diagnosis_data_source_id,omitempty"`
	DiagnosisId              uint64   `protobuf:"varint,3,opt,name=diagnosis_id,json=diagnosisId,proto3" json:"diagnosis_id,omitempty"`
	ProjectId                uint64   `protobuf:"varint,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	RecordId                 string   `protobuf:"bytes,5,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	JiraId                   string   `protobuf:"bytes,6,opt,name=jira_id,json=jiraId,proto3" json:"jira_id,omitempty"`
	CreatedAt                int64    `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                int64    `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *RelDiagnosisDataSource) Reset()         { *m = RelDiagnosisDataSource{} }
func (m *RelDiagnosisDataSource) String() string { return proto.CompactTextString(m) }
func (*RelDiagnosisDataSource) ProtoMessage()    {}
func (*RelDiagnosisDataSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{4}
}

func (m *RelDiagnosisDataSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelDiagnosisDataSource.Unmarshal(m, b)
}
func (m *RelDiagnosisDataSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelDiagnosisDataSource.Marshal(b, m, deterministic)
}
func (m *RelDiagnosisDataSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelDiagnosisDataSource.Merge(m, src)
}
func (m *RelDiagnosisDataSource) XXX_Size() int {
	return xxx_messageInfo_RelDiagnosisDataSource.Size(m)
}
func (m *RelDiagnosisDataSource) XXX_DiscardUnknown() {
	xxx_messageInfo_RelDiagnosisDataSource.DiscardUnknown(m)
}

var xxx_messageInfo_RelDiagnosisDataSource proto.InternalMessageInfo

func (m *RelDiagnosisDataSource) GetRelDiagnosisDataSourceId() uint64 {
	if m != nil {
		return m.RelDiagnosisDataSourceId
	}
	return 0
}

func (m *RelDiagnosisDataSource) GetDiagnosisDataSourceId() uint64 {
	if m != nil {
		return m.DiagnosisDataSourceId
	}
	return 0
}

func (m *RelDiagnosisDataSource) GetDiagnosisId() uint64 {
	if m != nil {
		return m.DiagnosisId
	}
	return 0
}

func (m *RelDiagnosisDataSource) GetProjectId() uint64 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *RelDiagnosisDataSource) GetRecordId() string {
	if m != nil {
		return m.RecordId
	}
	return ""
}

func (m *RelDiagnosisDataSource) GetJiraId() string {
	if m != nil {
		return m.JiraId
	}
	return ""
}

func (m *RelDiagnosisDataSource) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *RelDiagnosisDataSource) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type RelDiagnosisDataSourceForUpsert struct {
	RelDiagnosisDataSourceId uint64   `protobuf:"varint,1,opt,name=rel_diagnosis_data_source_id,json=relDiagnosisDataSourceId,proto3" json:"rel_diagnosis_data_source_id,omitempty"`
	DiagnosisDataSourceId    uint64   `protobuf:"varint,2,opt,name=diagnosis_data_source_id,json=diagnosisDataSourceId,proto3" json:"diagnosis_data_source_id,omitempty"`
	DiagnosisId              uint64   `protobuf:"varint,3,opt,name=diagnosis_id,json=diagnosisId,proto3" json:"diagnosis_id,omitempty"`
	ProjectId                uint64   `protobuf:"varint,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ResourceType             string   `protobuf:"bytes,5,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceName             string   `protobuf:"bytes,6,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *RelDiagnosisDataSourceForUpsert) Reset()         { *m = RelDiagnosisDataSourceForUpsert{} }
func (m *RelDiagnosisDataSourceForUpsert) String() string { return proto.CompactTextString(m) }
func (*RelDiagnosisDataSourceForUpsert) ProtoMessage()    {}
func (*RelDiagnosisDataSourceForUpsert) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{5}
}

func (m *RelDiagnosisDataSourceForUpsert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelDiagnosisDataSourceForUpsert.Unmarshal(m, b)
}
func (m *RelDiagnosisDataSourceForUpsert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelDiagnosisDataSourceForUpsert.Marshal(b, m, deterministic)
}
func (m *RelDiagnosisDataSourceForUpsert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelDiagnosisDataSourceForUpsert.Merge(m, src)
}
func (m *RelDiagnosisDataSourceForUpsert) XXX_Size() int {
	return xxx_messageInfo_RelDiagnosisDataSourceForUpsert.Size(m)
}
func (m *RelDiagnosisDataSourceForUpsert) XXX_DiscardUnknown() {
	xxx_messageInfo_RelDiagnosisDataSourceForUpsert.DiscardUnknown(m)
}

var xxx_messageInfo_RelDiagnosisDataSourceForUpsert proto.InternalMessageInfo

func (m *RelDiagnosisDataSourceForUpsert) GetRelDiagnosisDataSourceId() uint64 {
	if m != nil {
		return m.RelDiagnosisDataSourceId
	}
	return 0
}

func (m *RelDiagnosisDataSourceForUpsert) GetDiagnosisDataSourceId() uint64 {
	if m != nil {
		return m.DiagnosisDataSourceId
	}
	return 0
}

func (m *RelDiagnosisDataSourceForUpsert) GetDiagnosisId() uint64 {
	if m != nil {
		return m.DiagnosisId
	}
	return 0
}

func (m *RelDiagnosisDataSourceForUpsert) GetProjectId() uint64 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *RelDiagnosisDataSourceForUpsert) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *RelDiagnosisDataSourceForUpsert) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func init() {
	proto.RegisterType((*Diagnosis)(nil), "diagnosis.Diagnosis")
	proto.RegisterType((*DiagnosisForUpsert)(nil), "diagnosis.DiagnosisForUpsert")
	proto.RegisterType((*DiagnosisDataSource)(nil), "diagnosis.DiagnosisDataSource")
	proto.RegisterType((*DiagnosisDataSourceForUpsert)(nil), "diagnosis.DiagnosisDataSourceForUpsert")
	proto.RegisterType((*RelDiagnosisDataSource)(nil), "diagnosis.RelDiagnosisDataSource")
	proto.RegisterType((*RelDiagnosisDataSourceForUpsert)(nil), "diagnosis.RelDiagnosisDataSourceForUpsert")
}

func init() { proto.RegisterFile("entities.proto", fileDescriptor_a5f7344b79fcc63d) }

var fileDescriptor_a5f7344b79fcc63d = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x54, 0xb1, 0x6e, 0xd4, 0x40,
	0x10, 0x95, 0x7d, 0x77, 0xce, 0x79, 0x12, 0x28, 0x16, 0x01, 0x96, 0x12, 0xc4, 0x71, 0x34, 0xd7,
	0x10, 0x17, 0x14, 0x11, 0x0d, 0xd2, 0x41, 0x84, 0xe4, 0x86, 0xc2, 0x81, 0x86, 0xc6, 0x5a, 0x7b,
	0x47, 0x66, 0x8f, 0xd8, 0xbb, 0xda, 0xdd, 0x93, 0x72, 0x5f, 0x43, 0x47, 0xc1, 0x8f, 0xf0, 0x19,
	0xfc, 0x0a, 0xf2, 0x9e, 0xcf, 0x76, 0x8c, 0xe5, 0x54, 0x48, 0xa4, 0xf3, 0xbc, 0x37, 0xe3, 0x37,
	0xf3, 0x66, 0xb4, 0xf0, 0x10, 0x4b, 0xc3, 0x0d, 0x47, 0x7d, 0x2e, 0x95, 0x30, 0x82, 0xf8, 0x8c,
	0xd3, 0xbc, 0x14, 0x9a, 0xeb, 0xe5, 0x77, 0x07, 0xfc, 0xcb, 0x43, 0x44, 0x5e, 0xc0, 0x49, 0x43,
	0x25, 0x9c, 0x05, 0xce, 0xc2, 0x59, 0x4d, 0xe3, 0xe3, 0x06, 0x8b, 0x18, 0x79, 0x06, 0x20, 0x95,
	0xd8, 0x60, 0x66, 0xaa, 0x04, 0xd7, 0x26, 0xf8, 0x35, 0x12, 0x31, 0x42, 0x60, 0x5a, 0xd2, 0x02,
	0x83, 0xc9, 0xc2, 0x59, 0xf9, 0xb1, 0xfd, 0xae, 0x4a, 0x32, 0x85, 0xd4, 0x20, 0x4b, 0xa8, 0x09,
	0xa6, 0x0b, 0x67, 0x35, 0x89, 0xfd, 0x1a, 0x59, 0x9b, 0x8a, 0xde, 0x4a, 0x76, 0xa0, 0x67, 0x7b,
	0xba, 0x46, 0xd6, 0x66, 0xb9, 0x01, 0xd2, 0x34, 0xf8, 0x41, 0xa8, 0xcf, 0x52, 0xa3, 0x32, 0xff,
	0xa6, 0xd3, 0xe5, 0x6f, 0x07, 0x1e, 0x35, 0x62, 0x97, 0xd4, 0xd0, 0x2b, 0xb1, 0x55, 0x19, 0x92,
	0x0b, 0x08, 0x5a, 0x35, 0x46, 0x0d, 0x4d, 0xb4, 0x25, 0x5a, 0xe5, 0xc7, 0xec, 0xef, 0xb2, 0x8e,
	0x88, 0xdb, 0xb1, 0x63, 0x01, 0xc7, 0x0c, 0x75, 0xa6, 0xb8, 0x34, 0x5c, 0x94, 0xb5, 0x7e, 0x17,
	0x22, 0xa7, 0xe0, 0x17, 0xf4, 0x26, 0xd1, 0x99, 0x50, 0x68, 0xfd, 0x72, 0xe3, 0x79, 0x41, 0x6f,
	0xae, 0xaa, 0xb8, 0xe7, 0xe6, 0x6c, 0xdc, 0x4d, 0xaf, 0xef, 0xe6, 0x4f, 0x07, 0xce, 0x06, 0x26,
	0x6c, 0x8d, 0xfd, 0x8f, 0x46, 0x5d, 0xfe, 0x72, 0xe1, 0x49, 0x8c, 0xd7, 0x43, 0x1b, 0x79, 0x0b,
	0x67, 0x0a, 0xaf, 0x93, 0x3b, 0x5a, 0x0d, 0xd4, 0x60, 0x75, 0xc4, 0x46, 0xc7, 0x74, 0xc7, 0xc6,
	0xec, 0x1f, 0xde, 0xe4, 0xae, 0xc3, 0x9b, 0xf6, 0x0f, 0xef, 0x14, 0x7c, 0x85, 0x99, 0x50, 0xac,
	0x62, 0x67, 0xd6, 0x92, 0xf9, 0x1e, 0x88, 0x18, 0x79, 0x0a, 0x47, 0x1b, 0xae, 0x68, 0x45, 0x79,
	0x96, 0xf2, 0xaa, 0x70, 0xff, 0xd3, 0xce, 0xda, 0x8f, 0xc6, 0xd7, 0x3e, 0xef, 0xaf, 0xfd, 0x87,
	0x0b, 0xcf, 0x87, 0x9d, 0x6c, 0x37, 0x7f, 0x8f, 0x2d, 0x7d, 0x09, 0x0f, 0x14, 0xd6, 0x6a, 0x66,
	0x27, 0xb1, 0xb6, 0xf5, 0xe4, 0x00, 0x7e, 0xda, 0x49, 0xbc, 0x95, 0x64, 0x2f, 0xd5, 0xbb, 0x9d,
	0xf4, 0x91, 0x16, 0xf8, 0xee, 0xcd, 0x97, 0x8b, 0x9c, 0x9b, 0xaf, 0xdb, 0xf4, 0x3c, 0x13, 0x45,
	0xf8, 0x7e, 0x97, 0xa2, 0x5a, 0xe7, 0x58, 0x9a, 0xb0, 0xe0, 0x85, 0xd0, 0xf4, 0x55, 0xd3, 0x54,
	0x28, 0xbf, 0xe5, 0xa1, 0x4c, 0xc3, 0x06, 0x48, 0x3d, 0xfb, 0xb8, 0xbe, 0xfe, 0x13, 0x00, 0x00,
	0xff, 0xff, 0xc6, 0x25, 0xc1, 0x36, 0x6e, 0x05, 0x00, 0x00,
}
